name: openfeature_provider_intellitoggle
description: Official IntelliToggle provider for the OpenFeature Dart Server SDK.
version: 0.0.5
homepage: https://intellitoggle.com
repository: https://github.com/aortem/intellitoggle-openfeature-provider-dart-server

environment:
  sdk: ^3.9.2

dependencies:
  openfeature_dart_server_sdk: ^0.0.13
  http: ^1.5.0
  meta: ^1.17.0

dev_dependencies:
  ds_tools_testing: ^0.1.0
  test: ^1.25.2

dependency_overrides:
  openfeature_dart_server_sdk: ^0.0.13


