name: openfeature_provider_intellitoggle
description: Official IntelliToggle provider for the OpenFeature Dart Server SDK.
version: 0.0.6
homepage: https://intellitoggle.com
repository: https://github.com/aortem/intellitoggle-openfeature-provider-dart-server

environment:
  sdk: ^3.10.3

dependencies:
  openfeature_dart_server_sdk: ^0.0.15
  http: ^1.6.0
  meta: ^1.17.0
  jwt_generator: ^0.0.8
  grpc: ^5.1.0
  protobuf: ^6.0.0
  fixnum: ^1.1.1

dev_dependencies:
  ds_tools_testing: ^0.1.4 #Standard Dart Team Testing Tools
  gherkin: ^3.1.0
  test: ^1.28.0
  path: ^1.9.1
